### ISSUE TITLE
NEURON files should be copied to stimfolder

### ISSUE THREAD

**Issue by Kinway25** [SFB-ELAINE/OSS-DBSv2#39]
Currently it uses the active MATLAB path. Should use `output_path`

**Comment by j-zimmermann** [comment]
Do you mean the .hoc files etc?

The files get copied to a folder called `neuron_model` (which is inside the current workdir, obtained by `os.getcwd()`) where they are compiled.

I changed this path to the output path. Is that what you had in mind?

**Comment by Kinway25** [comment]
exactly. In general, we should not use `os.getcwd()` at all
