### ISSUE TITLE
Synthseg segmask recalculation

### ISSUE THREAD

**Issue by sahinia** [SFB-ELAINE/OSS-DBSv2#59]
Hi, I am calculating efields using OSS DBS for multiple lead group files. This is for the same patient group at different timepoints. OSS seems to recalculate segmasks again for each lead group, even though segmasks were already available in the previous lead group. Would it be possible to reuse the same segmask per patient to save time?

Thanks for taking into consideration!
Best,
Aysu

**Comment by Kinway25** [comment]
Resolved (on Lead-DBS side). Same as SPM, SynthSeg now stores raw segmasks in Coregistration/
